# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tabmeta',
                'doc_host': 'https://gautam-e.github.io',
                'git_url': 'https://github.com/gautam-e/tabmeta',
                'lib_path': 'tabmeta'},
  'syms': {'tabmeta.core': {'tabmeta.core.foo': ('core.html#foo', 'tabmeta/core.py')}}}
